# Generated by Django 4.0.5 on 2022-06-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cAddr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cBrithday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cEmail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cPhone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cSex',
        ),
    ]
