# Generated by Django 4.0.5 on 2022-06-17 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_student_caddr_student_cemail_student_cphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cBrithday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
